version: '3'
services:
  stack_kotlin:
    build: stack_kotlin
    ports:
     - "9001:8080"
  stack_python:
    build: stack_python
    ports:
     - "9002:8080"
  stack_typescript:
    build: stack_typescript
    ports:
     - "9003:3001"
  db_mysql:
    image: mysql:5.7
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: ts_user
      MYSQL_PASSWORD: ts_pw
      MYSQL_DATABASE: ts_db
    ports:
      - "3333:3306"
    restart: always
